name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for switching branches

      - name: Install ImageMagick (Fix for rmagick)
        run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev imagemagick

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Build Jekyll Site with Debugging
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --trace --verbose

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages

      - name: Copy required folders from main to gh-pages
        run: |
          echo "Before copying - Listing existing files:"
          ls -R _data _includes _layouts _posts || echo "No existing files"

          git checkout main -- _data/comments _includes _layouts _posts
          mkdir -p _data/comments _includes _layouts _posts  # Ensure directories exist

          echo "After ensuring directories exist:"
          ls -R _data _includes _layouts _posts || echo "No files"

          rsync -av --progress _data/comments/ _data/comments/
          rsync -av --progress _includes/ _includes/
          rsync -av --progress _layouts/ _layouts/
          rsync -av --progress _posts/ _posts/

          echo "After copying - Listing files:"
          ls -R _data _includes _layouts _posts || echo "No files copied"

          git add -f _data/comments _includes _layouts _posts
          git commit -m "Sync site data from main" || echo "No changes to commit"

      - name: Push changes to gh-pages
        run: |
          git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to gh-pages
          folder: _site  # Deploy built Jekyll site
          token: ${{ secrets.GH_PAT }}  # Use your Personal Access Token
